### ISSUE TITLE
Local fontsize renders inconsistentl on diffrent backends

### ISSUE THREAD

**Issue by jeffreyrosenbluth** [diagrams/diagrams-lib#243]
Local font scaling on svg, cairo, rasterific and canvas produced different results.
rasterific and canvas are similar. 
```
eff = text "F" <> square 1

 example = hcat
   [eff, eff # scale 2, eff # scaleX 2, eff # scaleY 2, eff # rotateBy (1/12)]
         # fontSize (Local 1)
```

**Comment by cchalmers** [comment]
I'm getting reasonably consistent results:

svg
![svg](https://cloud.githubusercontent.com/assets/1354887/6772665/2a44a87c-d0fb-11e4-948a-3518d7877a51.png)

rasterific 
![rasterific](https://cloud.githubusercontent.com/assets/1354887/6772667/2f424906-d0fb-11e4-8b52-9c916f286b78.png)

pgf
![pgf](https://cloud.githubusercontent.com/assets/1354887/6772669/36e62d80-d0fb-11e4-9333-b18aab4645c1.png)

html5
![html5](https://cloud.githubusercontent.com/assets/1354887/6772670/3f3ea912-d0fb-11e4-9064-7064822e3381.png)

Note that the `fontSize (local 1)` doesn't have the scales applied because it's applied after the transforms (I think this is different from old behaviour). If the font size is transformed too I get these:

svg
![svg](https://cloud.githubusercontent.com/assets/1354887/6772648/e4c58e88-d0fa-11e4-96ef-a02de9aa19e4.png)

rasterific
![rasterific](https://cloud.githubusercontent.com/assets/1354887/6772650/e620e016-d0fa-11e4-9fab-b3c08dd42a8d.png)

pgf
![pgf](https://cloud.githubusercontent.com/assets/1354887/6772652/e7a244ca-d0fa-11e4-8631-3897c93aa431.png)

html5
![html5](https://cloud.githubusercontent.com/assets/1354887/6772653/e91efc80-d0fa-11e4-85e3-fb687e72cb00.png)

I haven't got Cairo installed here so I haven't tested it. What are you seeing?

**Comment by cchalmers** [comment]
Sorry, I'm blind -- SVG is clearly wrong. I even made an issue about it diagrams/diagrams-svg#66. I think it has something to do with the weird way SVG handles font-size precedence. I didn't look at it properly.

**Comment by jeffreyrosenbluth** [comment]
Ah, I didn't realize the semantics changed. Thanks for putting together this comparison.
So the only thing broken is diagrams-svg. I guess we should change the user manual example to
```
eff = text "F" <> square 1 # fontSize (Local 1)
 example = hcat
   [eff, eff # scale 2, eff # scaleX 2, eff # scaleY 2, eff # rotateBy (1/12)]
        
```

**Comment by cchalmers** [comment]
In you're example you're only changing the font size of the square :)

Note that the default font size is `local 1` anyway, but it seems like a good idea to make it explicit in case it ever changes.

**Comment by byorgey** [comment]
Aha, I was confused, thanks all!

**Comment by jeffreyrosenbluth** [comment]
Still not sure his is correct. What should this look like?
```
eff = text "F" <> square 1 # fontSize (Normalized 0.1)
 example = hcat
   [eff, eff # scale 2, eff # scaleX 2, eff # scaleY 2, eff # rotateBy (1/12)]
```

**Comment by jeffreyrosenbluth** [comment]
Never mind, I was missing the parenthesis.
```eff = (text "F" <> square 1) # fontSize (Normalized 0.1)```
