### ISSUE TITLE
Please remove dependency on deprecated system-filepath package

### ISSUE THREAD

**Issue by peti** [diagrams/diagrams-lib#258]
`system-filepath` has been deprecated: http://packdeps.haskellers.com/feed?needle=diagrams-lib. Would you mind updating this package so that it works with `FilePath = String` or, alternatively, switch to some other library for getting a path abstraction?

**Comment by byorgey** [comment]
I tried doing this at some point in the past but it was annoyingly difficult because we also depend on `fsnotify` which in turn depended on `system-filepath`.  But I see that the newest version of `fsnotify` no longer depends on `system-filepath`, so addressing https://github.com/diagrams/diagrams-lib/issues/259 should fix this as well.  I think I should have some time to get to it later today.

**Comment by peti** [comment]
Very cool, thank you! `diagrams-lib` is currently broken in NixOS, which is really bad since it's a popular package. It would be great to get a fix for that issue soon'ish.
